-- MySQL Script generated by MySQL Workbench
-- Wed Jun 30 17:37:38 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pizzeria` ;

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzeria` DEFAULT CHARACTER SET utf8 ;
USE `pizzeria` ;

-- -----------------------------------------------------
-- Table `pizzeria`.`provincia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria`.`provincia` ;

CREATE TABLE IF NOT EXISTS `pizzeria`.`provincia` (
  `id_provincia` INT(11) NOT NULL,
  `nombre_provincia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_provincia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `provincia` ON `pizzeria`.`provincia` (`nombre_provincia` ASC);


-- -----------------------------------------------------
-- Table `pizzeria`.`localidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria`.`localidad` ;

CREATE TABLE IF NOT EXISTS `pizzeria`.`localidad` (
  `id_localidad` INT(11) NOT NULL AUTO_INCREMENT,
  `localidad` VARCHAR(45) NOT NULL,
  `provincia_id_provincia` INT(11) NOT NULL,
  PRIMARY KEY (`id_localidad`, `provincia_id_provincia`),
  CONSTRAINT `fk_localidad_provincia1`
    FOREIGN KEY (`provincia_id_provincia`)
    REFERENCES `pizzeria`.`provincia` (`id_provincia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_localidad_provincia1_idx` ON `pizzeria`.`localidad` (`provincia_id_provincia` ASC);


-- -----------------------------------------------------
-- Table `pizzeria`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria`.`cliente` ;

CREATE TABLE IF NOT EXISTS `pizzeria`.`cliente` (
  `id_cliente` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_cl` VARCHAR(45) NOT NULL,
  `apellido_cl` VARCHAR(45) NOT NULL,
  `direccion_cl` VARCHAR(100) NOT NULL,
  `localidad_id_localidad` INT(11) NOT NULL,
  `cod_postal_cl` VARCHAR(10) NOT NULL,
  `email_cl` VARCHAR(45) NOT NULL,
  `telefono_cl` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_cliente`, `localidad_id_localidad`),
  CONSTRAINT `fk_cliente_localidad`
    FOREIGN KEY (`localidad_id_localidad`)
    REFERENCES `pizzeria`.`localidad` (`id_localidad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_cliente_localidad_idx` ON `pizzeria`.`cliente` (`localidad_id_localidad` ASC) ;


-- -----------------------------------------------------
-- Table `pizzeria`.`empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria`.`empleado` ;

CREATE TABLE IF NOT EXISTS `pizzeria`.`empleado` (
  `id_empleado` INT(11) NOT NULL AUTO_INCREMENT,
  `cat_empleado` ENUM('cocinero', 'repartidor') NULL,
  `nombre_emp` VARCHAR(100) NULL,
  `apellido_emp` VARCHAR(100) NULL,
  `nif_emp` VARCHAR(9) NULL,
  `telefono` VARCHAR(15) NULL,
  PRIMARY KEY (`id_empleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`tienda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria`.`tienda` ;

CREATE TABLE IF NOT EXISTS `pizzeria`.`tienda` (
  `id_tienda` INT(11) NOT NULL AUTO_INCREMENT,
  `direccion_tienda` VARCHAR(100) NULL DEFAULT NULL,
  `cod_postal` VARCHAR(10) NULL DEFAULT NULL,
  `localidad_id_localidad` INT(11) NOT NULL,
  PRIMARY KEY (`id_tienda`, `localidad_id_localidad`),
  CONSTRAINT `fk_tienda_localidad1`
    FOREIGN KEY (`localidad_id_localidad`)
    REFERENCES `pizzeria`.`localidad` (`id_localidad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_tienda_localidad1_idx` ON `pizzeria`.`tienda` (`localidad_id_localidad` ASC) ;


-- -----------------------------------------------------
-- Table `pizzeria`.`comanda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria`.`comanda` ;

CREATE TABLE IF NOT EXISTS `pizzeria`.`comanda` (
  `id_comanda` INT(11) NOT NULL AUTO_INCREMENT,
  `entrega` ENUM('tienda', 'domicilio') NOT NULL,
  `cliente_id_cliente` INT(11) NOT NULL,
  `tienda_id_tienda` INT(11) NOT NULL,
  `empleados_id_empleados` INT(11) NOT NULL,
  PRIMARY KEY (`id_comanda`, `cliente_id_cliente`, `tienda_id_tienda`, `empleados_id_empleados`),
  CONSTRAINT `fk_comanda_cliente1`
    FOREIGN KEY (`cliente_id_cliente`)
    REFERENCES `pizzeria`.`cliente` (`id_cliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comanda_empleados1`
    FOREIGN KEY (`empleados_id_empleados`)
    REFERENCES `pizzeria`.`empleado` (`id_empleado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comanda_tienda1`
    FOREIGN KEY (`tienda_id_tienda`)
    REFERENCES `pizzeria`.`tienda` (`id_tienda`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_comanda_cliente1_idx` ON `pizzeria`.`comanda` (`cliente_id_cliente` ASC);

CREATE INDEX `fk_comanda_tienda1_idx` ON `pizzeria`.`comanda` (`tienda_id_tienda` ASC);

CREATE INDEX `fk_comanda_empleados1_idx` ON `pizzeria`.`comanda` (`empleados_id_empleados` ASC) ;


-- -----------------------------------------------------
-- Table `pizzeria`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria`.`categoria` ;

CREATE TABLE IF NOT EXISTS `pizzeria`.`categoria` (
  `id_categoria` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_categorias` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pizzeria`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria`.`producto` ;

CREATE TABLE IF NOT EXISTS `pizzeria`.`producto` (
  `id_producto` INT(11) NOT NULL AUTO_INCREMENT,
  `categoria_id_categoria` INT(11) NOT NULL,
  `nombre_producto` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `link_imagen` VARCHAR(255) NULL DEFAULT NULL,
  `precio` DECIMAL(5,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id_producto`, `categoria_id_categoria`),
  CONSTRAINT `fk_producto_categoria1`
    FOREIGN KEY (`categoria_id_categoria`)
    REFERENCES `pizzeria`.`categoria` (`id_categoria`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_producto_categoria1_idx` ON `pizzeria`.`producto` (`categoria_id_categoria` ASC) ;

CREATE INDEX `nombre_producto` ON `pizzeria`.`producto` (`nombre_producto` ASC) ;


-- -----------------------------------------------------
-- Table `pizzeria`.`comanda_listado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria`.`comanda_listado` ;

CREATE TABLE IF NOT EXISTS `pizzeria`.`comanda_listado` (
  `comanda_id_comanda` INT(11) NOT NULL,
  `producto_id_producto` INT(11) NOT NULL,
  `cantidad` INT(11) NOT NULL,
  PRIMARY KEY (`comanda_id_comanda`, `producto_id_producto`, `cantidad`),
  CONSTRAINT `fk_comanda_listado_comanda1`
    FOREIGN KEY (`comanda_id_comanda`)
    REFERENCES `pizzeria`.`comanda` (`id_comanda`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comanda_listado_producto1`
    FOREIGN KEY (`producto_id_producto`)
    REFERENCES `pizzeria`.`producto` (`id_producto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_comanda_listado_producto1_idx` ON `pizzeria`.`comanda_listado` (`producto_id_producto` ASC) ;

CREATE INDEX `fk_comanda_listado_comanda1_idx` ON `pizzeria`.`comanda_listado` (`comanda_id_comanda` ASC) ;


-- -----------------------------------------------------
-- Table `pizzeria`.`a_domicilio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria`.`a_domicilio` ;

CREATE TABLE IF NOT EXISTS `pizzeria`.`a_domicilio` (
  `comanda_listado_comanda_id_comanda` INT(11) NOT NULL,
  `empleados_id_empleados` INT(11) NOT NULL,
  `hora_reparto` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`comanda_listado_comanda_id_comanda`, `empleados_id_empleados`),
  CONSTRAINT `fk_a_domicilio_comanda_listado1`
    FOREIGN KEY (`comanda_listado_comanda_id_comanda`)
    REFERENCES `pizzeria`.`comanda_listado` (`comanda_id_comanda`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_a_domicilio_empleados1`
    FOREIGN KEY (`empleados_id_empleados`)
    REFERENCES `pizzeria`.`empleado` (`id_empleado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_a_domicilio_empleados1_idx` ON `pizzeria`.`a_domicilio` (`empleados_id_empleados` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
