-- MySQL Script generated by MySQL Workbench
-- Tue Jun 22 16:34:08 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ULLERES
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ULLERES
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ULLERES` DEFAULT CHARACTER SET utf8 ;
USE `ULLERES` ;

-- -----------------------------------------------------
-- Table `ULLERES`.`proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ULLERES`.`proveedor` ;

CREATE TABLE IF NOT EXISTS `ULLERES`.`proveedor` (
  `id_proveedor` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `direccion_calle` VARCHAR(45) NOT NULL,
  `numero` TINYINT(4) NULL,
  `pis` TINYINT(3) NULL,
  `porta` TINYINT(3) NULL,
  `direccion_extra` VARCHAR(45) NULL,
  `ciutat` VARCHAR(45) NULL,
  `codi_postal` TINYINT(5) NULL,
  `pais` VARCHAR(45) NULL,
  PRIMARY KEY (`id_proveedor`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ULLERES`.`marca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ULLERES`.`marca` ;

CREATE TABLE IF NOT EXISTS `ULLERES`.`marca` (
  `id_marca` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  `proveedor_id_proveedor` INT NOT NULL,
  PRIMARY KEY (`id_marca`),
  INDEX `fk_marca_proveedor_idx` (`proveedor_id_proveedor` ASC),
  CONSTRAINT `fk_marca_proveedor`
    FOREIGN KEY (`proveedor_id_proveedor`)
    REFERENCES `ULLERES`.`proveedor` (`id_proveedor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ULLERES`.`ulleres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ULLERES`.`ulleres` ;

CREATE TABLE IF NOT EXISTS `ULLERES`.`ulleres` (
  `id_ulleres` INT NOT NULL AUTO_INCREMENT,
  `grad_cristal_izq` DOUBLE(3,2) NOT NULL,
  `grad_cristal_der` DOUBLE(3,2) NOT NULL,
  `tipo_montura` ENUM('flotant', 'pasta', 'metálica') NOT NULL,
  `color_vidre_izq` VARCHAR(45) NULL DEFAULT 'transparente',
  `color_vidre_der` VARCHAR(45) NULL DEFAULT 'transparente',
  `color_montura` ENUM('negro', 'marrón', 'blanco', 'gris', 'rojo') NULL DEFAULT 'negro',
  `preu` DOUBLE(6,2) NOT NULL,
  `marca_id_marca` INT NOT NULL,
  PRIMARY KEY (`id_ulleres`),
  INDEX `fk_ulleres_marca1_idx` (`marca_id_marca` ASC),
  CONSTRAINT `fk_ulleres_marca1`
    FOREIGN KEY (`marca_id_marca`)
    REFERENCES `ULLERES`.`marca` (`id_marca`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ULLERES`.`clientes`
-- -----------------------------------------------------
-- ! NANCY - se ha reemplazado el TINYINT del campo 'teléfono' por INT
DROP TABLE IF EXISTS `ULLERES`.`clientes` ;

CREATE TABLE IF NOT EXISTS `ULLERES`.`clientes` (
  `id_clientes` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `direccion_postal` VARCHAR(120) NULL,
  `telefono` INT NULL,
  `email` VARCHAR(45) NOT NULL,
  `data_de_registre` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `recomendado_por` VARCHAR(45) NULL,
  PRIMARY KEY (`id_clientes`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ULLERES`.`empleados`
-- -----------------------------------------------------
-- ! NANCY - se ha reemplazado el TINYINT del campo 'teléfono' por INT
DROP TABLE IF EXISTS `ULLERES`.`empleados` ;

CREATE TABLE IF NOT EXISTS `ULLERES`.`empleados` (
  `id_empleados` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `direccion_postal` VARCHAR(120) NULL,
  `telefono` INT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id_empleados`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ULLERES`.`ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ULLERES`.`ventas` ;

CREATE TABLE IF NOT EXISTS `ULLERES`.`ventas` (
  `id_ventas` INT NOT NULL AUTO_INCREMENT,
  `empleados_id_empleados` INT NOT NULL,
  `clientes_id_clientes` INT NOT NULL,
  `ulleres_id_ulleres` INT NOT NULL,
  PRIMARY KEY (`id_ventas`, `empleados_id_empleados`, `clientes_id_clientes`, `ulleres_id_ulleres`),
  INDEX `fk_ventas_empleados1_idx` (`empleados_id_empleados` ASC),
  INDEX `fk_ventas_clientes1_idx` (`clientes_id_clientes` ASC),
  INDEX `fk_ventas_ulleres1_idx` (`ulleres_id_ulleres` ASC),
  CONSTRAINT `fk_ventas_empleados1`
    FOREIGN KEY (`empleados_id_empleados`)
    REFERENCES `ULLERES`.`empleados` (`id_empleados`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ventas_clientes1`
    FOREIGN KEY (`clientes_id_clientes`)
    REFERENCES `ULLERES`.`clientes` (`id_clientes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ventas_ulleres1`
    FOREIGN KEY (`ulleres_id_ulleres`)
    REFERENCES `ULLERES`.`ulleres` (`id_ulleres`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
